### ISSUE TITLE
As a designer, I can understand the difference between JavaScript and jQuery

### ISSUE THREAD

**Issue by heyitsolivia** [heyitsolivia/javascript-for-designers#4]
**Tasks**
- [ ] Explain what Javascript is
- [ ] Explain what jQuery is and its relation to JavaScript
- [ ] Provide examples to illustrate the differences
